# title: CSE598
# page-top-title: CSE598
# top-section-bg-text: Determining the layer structure and thickness using model-based
# white light interferometry
# home-subtitle: AI for Science
# copyright-text: '&copy; CMX 2024-2025. All Rights Reserved.'

title: s Homepage
page-top-title: 234
top-section-bg-text: Computer Science
home-subtitle: Sh
copyright-text: '&copy; Shunyao Wu 2024-2025. All Rights Reserved.'
