# title: CSE598
# page-top-title: CSE598
# top-section-bg-text: Determining the layer structure and thickness using model-based
# white light interferometry
# home-subtitle: AI for Science
# copyright-text: '&copy; CMX 2024-2025. All Rights Reserved.'

title: CSE598
page-top-title: CSE598
top-section-bg-text: Determining the layer structure and thickness using model-based white light interferometry
home-subtitle: AI for Science
copyright-text: '&copy;  2024-2025. All Rights Reserved.'
